baseURL = "http://moyers.dev/"
languageCode = "en-us"
title = "Josh Moyers"
theme = "moyers"
copyright = "Joshua Moyers"
enableGitInfo = "true"

[author]
	name = "Joshua Moyers"
	email = "josh@moyers.dev"

[params]
	dateformat = "January 2, 2006 at 3:04 PM"

[imaging]
	anchor = "smart"